apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-dp-app-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: validation-flow-migration
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: dp/environments/dev/datapower/
    repoURL: https://github.com/${GIT_ORG}/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
